version: "3.8"

services:
  frontend:
    image: tuyenhdt/my-f-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: tuyenhdt/my-f-backend:latest
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    env_file:
      - ./backend/.env.backend

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: NestJS
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: